# Use root/toor as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: radar

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  it-radar-backend:
    container_name: it-radar-backend
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: toor
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: radar
